drop table classroom;
drop table department;
drop table course;
drop table instructor;
drop table section;
drop table teaches;
drop table student;
drop table takes;
drop table advisor;
drop table time_slot;
drop table prereq